.TH BUCKLE "1" "September 2016" "Nostalgia bucklespring keyboard sound" "User Commands"
.SH NAME
buckle -  Nostalgia bucklespring keyboard sound
.SH SYNOPSIS
buckle [options]
.SH DESCRIPTION
Buckle emulates the sound of an old IBM Model-M space saver
bucklespring keyboard while typing within an X session.

It runs as a background process and plays back the sound of each key
pressed and released on the keyboard, just as if using an IBM Model-M.
The sound of each key has carefully been sampled, and is played back
while simulating the proper distance and direction for a realistic 3D
sound palette of pure nostalgic bliss.
.SH OPTIONS
.HP
\fB\-d\fR DEVICE
use OpenAL audio device DEVICE
.TP
\fB\-f\fR
use a fallback sound for unknown keys
.TP
\fB\-g\fR GAIN
set playback gain [0..100]
.TP
\fB\-h\fR
show help
.TP
\fB\-l\fR
list available openAL audio devices
.TP
\fB\-p\fR PATH
load .wav files from directory PATH
.TP
\fB\-s\fR WIDTH
set stereo width [0..100]
.TP
\fB\-v\fR
increase verbosity / debugging
.SH COPYRIGHT
Bucklespring was written by Ico Doornekamp and is published under the
terms of the GNU General Public License version 2.

This manual page was written by Dominik George for the Debian project.
